### PR TITLE
needed to cover init, all it does it simply pass back what ever it wa…

### PR DESCRIPTION
**Pull request by matthewphilyaw**
…s given so I missed it first time around

provides 100% coverage for this module.

### CODE REVIEW

**Comment by matthewphilyaw** [comment]
@copenhas just added one test, the init function doesn't do anything so the one test should cover it for now. If we use it in the future this test will break when we set the parameters.

**Comment by copenhas** [comment]
The Plug stuff doesn't define a default function already? I know a lot of elixir stuff provides default implementations.

**Comment by matthewphilyaw** [comment]
https://github.com/elixir-lang/plug

I believe you are required to implement both init and call, even the short example does this as well. I will check it out though. It's a spec more than anything so the things using your plug will call init, then call.

**Comment by matthewphilyaw** [comment]
http://hexdocs.pm/plug/Plug.Builder.html

We could do that then init would be optional. I think without it though you are required to define it. I have no issue doing this for both of them and see if the tests still pas they should.

**Comment by matthewphilyaw** [comment]
[Here](https://github.com/elixir-lang/plug/blob/master/lib/plug/head.ex) is one example of Plug.Head that is provided it defines the default as well, but did notice the behavior that was added.

Plug.Builder is one option as mentioned but not sure how idiomatic that is when the sole purpose is to not provide the default init.

**Comment by copenhas** [comment]
Cool, yeah I'm just thinking if it doesn't do anything then why implement and test it.

**Comment by matthewphilyaw** [comment]
It is called, so unless we use Plug.Builder it will need to be there. 

I'm kind of the opinion to keep as is. Seems more idiomatic. The more I looked into plug builder it does handle the default case but also injects a lot of other stuff not going to be used for this simple plug. 

The test also probably needs to stay cause while it seems trivial it's more of ok some one actually decides to add options the test will fail and they will need to make it pass plus other tests to cover the options hey put in. 

I know it seems odd but it maybe best for now.

**Pull request merged**
