### PR TITLE
Split project into two apps

### PR DESCRIPTION
**Pull request by copenhas**
Migrating towards umbrella project with two apps, one for game server and one for web server.
- [x] split app into two
- [x] make tests pass
- [x] migrate from phoenix models to straight ecto
- [x] ensure travis ci works completely
- [x] ensure coveralls works completely

### CODE REVIEW

**Comment by matthewphilyaw** [comment]
@copenhas I believe that phoenix models are straight ecto models. There is a use statement at the top but all it's doing is defining some common things I believe (if I remember correctly). All the validation and changeset is 100% ecto.

The use I'm talking about is [here](https://github.com/voluspa/yggdrasil/blob/copenhas/umbrella/apps/yggdrasil_web/web/models/user.ex#L2)

Also the session model is just there, probably doesn't need to move it's purely for login.

**Comment by copenhas** [comment]
Ok, I think I got everything working. Notice that we dropped a little coverage when we fully split. ExCoveralls doesn't report coverage of all the test combined there is a issues for this (https://github.com/parroty/excoveralls/issues/23).

Also I was running into issues with our app paths not being correct and coveralls.io not finding the source  files. I have submitted a PR (https://github.com/parroty/excoveralls/pull/42) for a potential fix to ExCoveralls.

**Comment by matthewphilyaw** [comment]
@copenhas I'm good with this do you want to squash this down to one commit or leave those two?

**Comment by copenhas** [comment]
I think it's better as two.

**Comment by matthewphilyaw** [comment]
Cool with that just wanted to make sure.

**Pull request merged**
