### PR TITLE
adding travis ci support

### PR DESCRIPTION
**Pull request by copenhas**

### CODE REVIEW

**Comment by matthewphilyaw** [comment]
Sweet that was something else I was going to do by the end of the day.

~~I added this for one of my projects here~~

~~https://github.com/matthewphilyaw/motor_hat/blob/master/.travis.yml~~

~~you may have to add before_script: bit to get it to compile. I also run tests in this one, but ignore the --no-start section.~~

I see that it built, maybe I had to add it because of the tests don't remember.

**Comment by copenhas** [comment]
Looks like it pulls deps and builds them during the build.

**Comment by copenhas** [comment]
Ok, sorry for the rebasing but was playing around a bit. Looks like running `ecto.create` is all that is needed. I also added an explicit postgresql version. At some point I might write up a docker file that uses these same versions so we can maybe use it for the local dev/test server.

**Comment by copenhas** [comment]
I'll add that this won't be enough to run acceptance tests, but it'll allow us to run the unit/intergration tests.

**Pull request merged**
